// <auto-generated />
namespace Pharmacy.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Form_OtM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Form_OtM));
        
        string IMigrationMetadata.Id
        {
            get { return "202102161341369_Form_OtM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
